from django import forms
from django.forms import ClearableFileInput, inlineformset_factory
from .models import Campaign, CampaignAsset, MediaLibraryAsset
from customers.models import Customer

class CampaignForm(forms.ModelForm):
    customers = forms.ModelMultipleChoiceField(
        queryset=Customer.objects.none(),
        widget=forms.SelectMultiple(attrs={'class': 'form-control select2'}),
        help_text="Select customers to receive this campaign. Opted-out customers will be automatically excluded."
    )

    class Meta:
        model = Campaign
        fields = [
            'name', 'subject', 'template_type', 'body_html',
            'hero_headline', 'hero_intro', 'hero_bullet_1', 'hero_bullet_2', 'hero_bullet_3',
            'hero_cta_label', 'hero_cta_url',
            'scheduled_for', 'include_unsubscribe'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. Q3 Promotion'}),
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email Subject'}),
            'body_html': forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'placeholder': 'Dear {{ contact_name }}, ...'}),
            'template_type': forms.Select(attrs={'class': 'form-select'}),
            'hero_headline': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Exclusive Offer for {{ company_name }}'}),
            'hero_intro': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Hi {{ contact_name }},\nShare your main offer here...'}),
            'hero_bullet_1': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Benefit 1'}),
            'hero_bullet_2': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Benefit 2'}),
            'hero_bullet_3': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Benefit 3'}),
            'hero_cta_label': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Schedule a Call'}),
            'hero_cta_url': forms.URLInput(attrs={'class': 'form-control', 'placeholder': 'https://...'}),
            'scheduled_for': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'include_unsubscribe': forms.CheckboxInput(attrs={'class': 'form-check-input'})
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['body_html'].required = False
        if user:
            # Salespersons can only email their assigned customers
            if user.role == 'salesperson':
                self.fields['customers'].queryset = Customer.objects.filter(salesperson=user, is_active=True)
            else:
                self.fields['customers'].queryset = Customer.objects.filter(is_active=True)

    def clean(self):
        cleaned = super().clean()
        if cleaned.get('template_type') in ['hero_promo', 'product_launch', 'newsletter_digest'] and not cleaned.get('body_html'):
            cleaned['body_html'] = '<!-- generated by Hero Promo Builder -->'
        return cleaned


class CampaignAssetForm(forms.ModelForm):
    class Meta:
        model = CampaignAsset
        fields = ['file', 'display_name', 'embed_inline', 'sort_order']
        widgets = {
            'file': ClearableFileInput(attrs={'accept': 'image/*'}),
            'display_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Optional image label'}),
            'embed_inline': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'sort_order': forms.NumberInput(attrs={'class': 'form-control', 'min': '0'}),
        }

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if not file:
            return file
        content_type = getattr(file, 'content_type', '') or ''
        if not content_type.startswith('image/'):
            raise forms.ValidationError('Only image files are supported for campaign embeds.')
        return file


CampaignAssetFormSet = inlineformset_factory(
    Campaign,
    CampaignAsset,
    form=CampaignAssetForm,
    fields=['file', 'display_name', 'embed_inline', 'sort_order'],
    extra=1,
    can_delete=True
)


class MediaLibraryAssetForm(forms.ModelForm):
    class Meta:
        model = MediaLibraryAsset
        fields = ['title', 'file']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'e.g. April Promo Banner'}),
            'file': ClearableFileInput(attrs={'accept': 'image/*', 'class': 'form-control'}),
        }

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if not file:
            return file
        content_type = getattr(file, 'content_type', '') or ''
        if not content_type.startswith('image/'):
            raise forms.ValidationError('Only image files are supported in the media library.')
        return file

class UnsubscribeForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly': 'readonly'}))
    reason = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'placeholder': 'Optional: Tell us why you are unsubscribing...'})
    )
